addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.5")
addSbtPlugin("org.bytedeco" % "sbt-javacpp" % "1.3")
//addSbtPlugin("org.scala-android" % "sbt-android" % "1.6.0-SNAPSHOT")
//addSbtPlugin("org.scala-android" % "sbt-android-protify" % "1.2.0-SNAPSHOT")
addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.5.20")
